services:
  - type: web
    name: capital-flask-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CAPITAL_API_KEY
        sync: false
      - key: CAPITAL_PASSWORD
        sync: false
      - key: CAPITAL_API_ENDPOINT
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
