services:
  - type: web
    name: capital-bot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0
    envVars:
      - key: CAPITAL_API_KEY
        fromEnvVar: CAPITAL_API_KEY
      - key: CAPITAL_EMAIL
        fromEnvVar: CAPITAL_EMAIL
      - key: CAPITAL_PASS
        fromEnvVar: CAPITAL_PASS
